# Generated by Django 5.2.5 on 2025-10-29 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('number_of_click', models.IntegerField(blank=True, default=0)),
            ],
        ),
    ]
